# Generated by Django 3.2.11 on 2022-01-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0002_auto_20220126_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
