# Generated by Django 3.2.11 on 2022-01-26 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0003_cartitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='price',
        ),
    ]
